### User API

### POST request to register
< {%
    const firstName = `FirstName_${$random.uuid}`;
    const lastName = `LastName_${$random.uuid}`;
    const email = $random.email;
    const password = `Pass_${$random.uuid.slice(0, 10)}`;
    request.variables.set("firstName", firstName);
    request.variables.set("lastName", lastName);
    request.variables.set("email", email);
    request.variables.set("password", password);
%}
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "first_name": "{{firstName}}",
  "last_name": "{{lastName}}",
  "email": "{{email}}",
  "password": "{{password}}"
}


###

### POST request to register (testUser)
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "first_name": "testUser",
  "last_name": "testUser",
  "email": "testUser@test.com",
  "password": "testUser123"
}


###

### GET request to login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "testUser@test.com",
  "password": "testUser123"
}

###

