### User API

### POST request to register
< {%
    const firstName = `FirstName_${$random.uuid}`;
    const lastName = `LastName_${$random.uuid}`;
    const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`;
    const password = `Pass_${$random.uuid}`;
    request.variables.set("firstName", firstName);
    request.variables.set("lastName", lastName);
    request.variables.set("email", email);
    request.variables.set("password", password);
%}
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "first_name": "{{firstName}}",
  "last_name": "{{lastName}}",
  "email": "{{email}}",
  "password": "{{password}}"
}


###

### GET request to login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

